use_frameworks!

platform :ios, '9.0'

target 'ZZCategoryKit_Example' do
  pod 'ZZCategoryKit', :path => '../'

  target 'ZZCategoryKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
